services:
  node:
    command: npm start
    environment:
      NODE_ENV: production
      PORT: 80
      DATABASE_URL: postgresql://admin:root@postgres:5432/myapp?schema=public
      JWT_SECRET: mysecret
      JWT_EXPIRES_IN: 1h
    ports:
      - "80:80"
